### ISSUE TITLE
getting error like this

### ISSUE THREAD

**Issue by mohanapriyakishoreson** [asinfotrack/yii2-comments#3]
Setting unknown property: asinfotrack\yii2\comments\widgets\Comments::model

**Comment by pasci84** [comment]
Hey there!
Thanks for your hint...do you have additional hint for your use case? A code snippet would be great to track down where the missing property is being set (the correct property would be `comments`)

**Comment by mohanapriyakishoreson** [comment]
![error](https://user-images.githubusercontent.com/50238126/57173655-f21df780-6e50-11e9-8212-26e0ac42aa90.PNG)

**Comment by mohanapriyakishoreson** [comment]
![error](https://user-images.githubusercontent.com/50238126/57173626-65733980-6e50-11e9-89e2-0ba1f64da648.PNG)
